[package]

name = "uax29"
version = "0.0.1"
authors = ["David Corbett <corbett.dav@husky.neu.edu>",
           "Mimi Lin <hloople@gmail.com>"]

[lib]
name = "uax29"
plugin = true

[dependencies]
lazy_static = "0.1.*"
